name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Create .env file
      run: |
        echo "POSTGRES_USER=user" > .env
        echo "POSTGRES_PASSWORD=password" >> .env
        echo "POSTGRES_DB=mydatabase" >> .env
        echo "POSTGRES_HOST=db" >> .env
        echo "POSTGRES_PORT=5432" >> .env

    - name: Connect to server and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/vboxuser/study-task
          docker-compose down
          git pull origin main
          mv /home/vboxuser/study-task/.github/workflows/.env /home/vboxuser/study-task/.env
          docker-compose up -d